import argparse
import json
import sys
import os
import tempfile
import subprocess
import winreg
import time
import re
from datetime import datetime

# =============================================================================
# UTILS & CONFIG
# =============================================================================

def load_config():
    """Loads DOORS launcher configuration from local config store.

    Reads optional settings from ~/.doors/config.json:
    - doors_data
    - doors_path

    Returns dict with keys: DOORS_DATA, DOORS_PATH.
    Missing config is allowed.
    """
    try:
        from credential_manager import get_credentials
    except ImportError:
        print(
            "ERROR: credential_manager module not found. "
            "Ensure credential_manager.py is in the same directory as doors_manager.py.",
            file=sys.stderr,
        )
        sys.exit(1)

    creds = get_credentials()
    if not creds:
        return {"DOORS_DATA": "", "DOORS_PATH": ""}

    config = {
        "DOORS_DATA": creds.get("doors_data", ""),
        "DOORS_PATH": creds.get("doors_path", ""),
    }
    print("DOORS launcher configuration loaded.", file=sys.stderr)
    return config

def find_doors_executable(config):
    """Finds DOORS executable via Config, Registry, or Common Paths."""
    # 1. Config override
    if config.get("DOORS_PATH") and os.path.exists(config.get("DOORS_PATH")):
        return config.get("DOORS_PATH")

    # 2. Environment Variable
    env_path = os.environ.get("DOORS_PATH")
    if env_path and os.path.exists(env_path):
        return env_path

    # 3. Registry
    try:
        key_path = r"SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\doors.exe"
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, key_path) as key:
            path, _ = winreg.QueryValueEx(key, None)
            if path and os.path.exists(path):
                return path
    except OSError:
        pass

    # 4. Common Paths
    common_paths = [
        r"C:\Program Files\IBM\Rational\DOORS\9.7\bin\doors.exe",
        r"C:\Program Files (x86)\IBM\Rational\DOORS\9.7\bin\doors.exe",
        r"C:\Program Files\IBM\Rational\DOORS\9.6\bin\doors.exe",
        r"C:\Program Files (x86)\IBM\Rational\DOORS\9.6\bin\doors.exe"
    ]
    for path in common_paths:
        if os.path.exists(path):
            return path
            
    return None

def parse_doors_url(url_input):
    """
    Parses a DOORS URL or module path.
    Supports doors:// URI and /Project/Path format.
    """
    cleaned = url_input.strip().strip("'").strip('"')
    
    # Try doors:// regex
    doors_match = re.search(r'(doors://[\w.:/-]+(?:\?[\w=&-]+)?)', cleaned)
    if doors_match:
        return doors_match.group(1)
        
    # Valid absolute path?
    if cleaned.startswith('/'):
        return cleaned
        
    return cleaned


def get_doors_pids():
    """Returns a set of running doors.exe PIDs."""
    pids = set()
    try:
        result = subprocess.run(
            ['tasklist', '/FI', 'IMAGENAME eq doors.exe', '/FO', 'CSV', '/NH'],
            capture_output=True,
            text=True,
            timeout=5,
        )
        for line in result.stdout.splitlines():
            row = line.strip().strip('"')
            if not row or 'no tasks are running' in row.lower():
                continue
            cols = [c.strip().strip('"') for c in line.split('","')]
            if len(cols) >= 2 and cols[0].lower() == 'doors.exe':
                try:
                    pids.add(int(cols[1]))
                except ValueError:
                    pass
    except Exception as e:
        print(f"WARNING: get_doors_pids query failed: {e}", file=sys.stderr)
        return set()
    return pids

# =============================================================================
# EXTRACTION LAYER (DXL Generation & Execution)
# =============================================================================

def generate_export_dxl(module_path, output_path, include_exit=True):
    """
    Generates a high-efficiency UNIVERSAL DXL script based on DOORS DXL Manual.
    Iterates all Attribute Definitions (AttrDef) to ensure complete schema extraction.
    When include_exit=False (COM mode), exit_ is omitted to keep DOORS running.
    """
    dxl_template = r"""
    // UNIVERSAL DOORS RAW DATA EXPORTER (Optimized)
    // ---------------------------------------------
    // Generated by AI Enabler
    
    // PERF: Disable instruction limit for large modules
    pragma runLim, 0
    
    // CONFIGURE
    string sModPath  = "{module_path}";
    string sOutPath  = "{output_path}";
    string sDonePath = sOutPath ".done";
    
    // BUFFERS
    Buffer g_buf = create;
    
    // HELPER: JSON ESCAPE
    void jsonEscape(Buffer b, string s) {{
        if (null s) {{ b += "null"; return; }}
        b += "\"";
        int len = length(s);
        int i;
        for (i = 0; i < len; i++) {{
            char c = s[i];
            if (c == '\"') b += "\\\"";
            else if (c == '\\') b += "\\\\";
            else if (c == '\n') b += "\\n";
            else if (c == '\r') b += "\\r";
            else if (c == '\t') b += "\\t";
            else if (c == '\b') b += "\\b";
            else if (c == '\f') b += "\\f";
            else if (c < ' ')  b += " "; 
            else b += c;
        }}
        b += "\"";
    }}

    // MAIN
    void doExport() {{
        // 1. OPEN MODULE (Read-Only)
        Module mod = read(sModPath, false, true);
        if (null mod) {{
            print "ERROR: Open failed for " sModPath "\n";
            halt;
        }}
        
        Stream outStream = write(sOutPath, 65001); // CP_UTF8
        if (null outStream) {{
            print "ERROR: Cannot write " sOutPath "\n";
            halt;
        }}
        
        // 2. PRE-CALCULATE ATTRIBUTE MAP (O(Attrs))
        // Filter out DXL attributes for performance and safety
        Skip skpSafeAttrs = createString();
        AttrDef ad;
        for ad in mod do {{
            if (!ad.object) continue;
            if (ad.dxl) continue; // Skip DXL attrs (Heavy/Unsafe)
            string sN = ad.name;
            put(skpSafeAttrs, sN, sN);
        }}
        
        // 3. EXPORT LOOP (O(Objects))
        g_buf += "[";
        Object obj;
        bool bFirstObj = true;
        
        for obj in mod do {{
            if (isDeleted(obj)) continue;
            
            if (!bFirstObj) g_buf += ",\n";
            bFirstObj = false;
            
            g_buf += "{{";
            
            // Meta
            g_buf += "\"id\":";
            jsonEscape(g_buf, identifier(obj));
            g_buf += ",\"abs_ref\":";
            string sAbs = probeAttr_(obj, "Absolute Number");
            g_buf += sAbs "";
            
            g_buf += ",\"attrs\":{{";
            
            bool bFirstAttr = true;
            string sName;
            string dummy;
            
            // Sparse iteration
            // Attr a; // REMOVED
            for sName in obj do {{
            // sName is the attribute Name
            // Filter DXL/System attrs
            if (!find(skpSafeAttrs, sName, dummy)) continue;
            
            string sVal = "";
            noError();
            sVal = probeAttr_(obj, sName);
            string err = lastError();
            if (!null err) continue;
            
            if (null sVal || sVal == "") continue;
            
            if (!bFirstAttr) g_buf += ",";
            bFirstAttr = false;
            
            jsonEscape(g_buf, sName);
            g_buf += ":";
            jsonEscape(g_buf, sVal);
        }}
            
            g_buf += "}}}}"; 
            
            // Flush Buffer (1MB)
            if (length(g_buf) > 1048576) {{
                outStream << g_buf;
                g_buf = "";
            }}
        }}
        
        g_buf += "]";
        outStream << g_buf;
        
        close outStream;
        delete g_buf;
        delete skpSafeAttrs;
        
        // 4. DONE SENTINEL
        Stream sDone = write(sDonePath, 65001);
        sDone << "DONE";
        close sDone;
        
    }}
    
    doExport();
    
    // Auto-Close DOORS after execution
    exit_;
    """
    # Safe path escaping for DXL: forward slashes + escape embedded double-quotes
    def _dxl_escape(s):
        return s.replace("\\", "/").replace('"', '\\"')
    safe_out = _dxl_escape(output_path)
    safe_mod = _dxl_escape(module_path)
    dxl = dxl_template.format(module_path=safe_mod, output_path=safe_out)
    if not include_exit:
        dxl = dxl.replace("exit_;", "// exit_ skipped (COM mode)")
    return dxl


def try_com_extraction(target_url, output_file):
    """
    Attempt extraction via COM/OLE on an already-running DOORS instance.
    Reuses existing session - no new process launch, no re-authentication.
    Returns (success: bool, message: str)
    """
    try:
        import win32com.client
    except ImportError:
        return False, "pywin32 not installed (pip install pywin32)"

    # STRICT: Check if DOORS process is actually running FIRST
    doors_pids_before = get_doors_pids()
    if not doors_pids_before:
        return False, "No doors.exe process running"

    # First try GetObject (never auto-launches)
    doors = None
    try:
        doors = win32com.client.GetObject(None, "DOORS.Application")
        doors.runStr('""')
    except Exception as e_get:
        # Compatibility fallback: some environments cannot resolve GetObject.
        # Try Dispatch, but guard against accidental second-instance launch.
        try:
            doors = win32com.client.Dispatch("DOORS.Application")
            doors.runStr('""')
            doors_pids_after = get_doors_pids()
            if len(doors_pids_after) > len(doors_pids_before):
                return False, (
                    "COM Dispatch started an additional DOORS instance; "
                    "aborted COM extraction to avoid duplicate session"
                )
        except Exception as e_dispatch:
            return False, (
                f"Cannot connect to DOORS via COM. "
                f"GetObject failed: {e_get}; Dispatch failed: {e_dispatch}"
            )

    output_abs = os.path.abspath(output_file)
    out_dir = os.path.dirname(output_abs)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    dxl_code = generate_export_dxl(target_url, output_abs, include_exit=False)

    print("COM: Connected to running DOORS instance.", file=sys.stderr)
    print(f"COM: Target Module: {target_url}", file=sys.stderr)
    print(f"COM: Output JSON:   {output_abs}", file=sys.stderr)

    # Write DXL to temp file and use runFile (more stable than runStr for large scripts)
    fd_dxl, dxl_path = tempfile.mkstemp(suffix=".dxl")
    os.close(fd_dxl)
    try:
        with open(dxl_path, 'w', encoding='utf-8') as f:
            f.write(dxl_code)

        print(f"COM: Executing DXL via runFile: {dxl_path}", file=sys.stderr)
        try:
            result = doors.runFile(dxl_path)
            if result:
                print(f"COM: DXL output: {result}", file=sys.stderr)
        except Exception as e:
            return False, f"COM DXL execution error: {e}"
    finally:
        try:
            os.remove(dxl_path)
        except:
            pass

    # === PHASE 1: Wait for DOORS to recover from large file processing ===
    # For large exports, DOORS may temporarily become unresponsive during I/O
    # Poll COM availability to detect when DOORS is ready after DXL execution
    # STRICTLY: Do NOT check file existence during this phase - only poll COM
    print("COM: DXL submitted. Waiting for DOORS to recover (polling COM availability)...", file=sys.stderr)
    
    com_recovery_max_retries = 60  # ~10 mins @ 10s interval
    com_recovery_interval = 10  # seconds
    com_recovered = False
    
    for attempt in range(1, com_recovery_max_retries + 1):
        time.sleep(com_recovery_interval)
        
        # Probe COM to see if DOORS is responsive again
        # DO NOT check file during polling - only verify COM availability
        try:
            doors.runStr('""')  # Simple ping
            print(f"COM: DOORS responsive again (attempt {attempt}). COM availability confirmed.", file=sys.stderr)
            com_recovered = True
            break
        except Exception as e:
            if attempt % 6 == 0:
                sys.stderr.write(f"\rCOM: Waiting for DOORS recovery... (attempt {attempt}/{com_recovery_max_retries})")
                sys.stderr.flush()
    
    if not com_recovered:
        print("\nCOM: Timeout waiting for DOORS to recover after DXL execution.", file=sys.stderr)
        return False, "COM: DOORS did not become responsive after DXL execution"
    
    print("COM: DOORS recovery confirmed. Proceeding to file validation.", file=sys.stderr)
    
    # === PHASE 2: Wait for file I/O to complete ===
    # After DOORS is responsive, allow 10 more seconds for file write to complete
    print("COM: Waiting 10s for DXL file I/O to complete...", file=sys.stderr)
    time.sleep(10)
    
    # === PHASE 3: Verify file existence (only after DOORS recovery confirmed) ===
    print("COM: Validating output file...", file=sys.stderr)
    if os.path.exists(output_abs) and os.path.getsize(output_abs) > 0:
        size_mb = os.path.getsize(output_abs) / (1024 * 1024)
        return True, f"COM extraction successful ({size_mb:.2f} MB): {output_abs}"
    else:
        # Cleanup sentinel if it exists
        done_marker = output_abs + ".done"
        if os.path.exists(done_marker):
            try:
                os.remove(done_marker)
            except OSError:
                pass
        
        return False, (
            f"COM: File was not created after DXL execution. "
            f"Possible causes: (1) Module access denied, (2) Module empty, (3) Path incorrect. "
            f"Please check module path and permissions, then retry extraction."
        )


def wait_for_doors_process(timeout_sec=20):
    """
    Waits for DOORS process (doors.exe) to become available.
    Returns True if process is detected, False on timeout.
    """
    start = time.time()
    while time.time() - start < timeout_sec:
        try:
            result = subprocess.run(['tasklist', '/FI', 'IMAGENAME eq doors.exe', '/FO', 'CSV', '/NH'],
                                   capture_output=True, text=True, timeout=5)
            if 'doors.exe' in result.stdout.lower():
                return True
        except Exception:
            pass
        time.sleep(1)
    return False


def run_extraction(target_url, output_file, keep_temp=False, no_gui=False):
    """
    Orchestrates the extraction process:
    1. Try COM/OLE reuse (fast path - seconds, requires running DOORS)
    2. Fallback: Launch DOORS GUI subprocess without credentials (manual login)
    3. After GUI launch, poll COM connection until user logs in or GUI completes

    When no_gui=True: only attempt COM reuse. If COM is unavailable, print a clear
    error message and exit — do NOT auto-launch the DOORS GUI. This is a safety net
    that must be explicitly dropped by the caller (i.e., the agent) only after user
    consent has been obtained.
    """
    # === FAST PATH: COM/OLE Reuse ===
    print("Attempting COM connection to running DOORS...", file=sys.stderr)
    success, msg = try_com_extraction(target_url, output_file)
    if success:
        print(msg, file=sys.stderr)
        return
    print(f"COM unavailable: {msg}.", file=sys.stderr)

    # === no_gui guard: stop here if GUI launch is not authorized ===
    if no_gui:
        print(
            "ERROR: DOORS is not running and --no-gui is set. "
            "GUI launch has been blocked.\n"
            "Action required: Start DOORS manually and log in, or re-run without --no-gui "
            "after obtaining explicit user consent for GUI launch.\n"
            "See SKILL.md §4.5.1 (Pre-Flight COM Check + User Consent Gate).",
            file=sys.stderr,
        )
        sys.exit(1)

    # === SLOW PATH: Launch GUI, then wait for COM ===
    print("Falling back to GUI launch.", file=sys.stderr)
    config = load_config()
    doors_exe = find_doors_executable(config)
    
    if not doors_exe:
        raise FileNotFoundError("DOORS executable not found. Configure doors_path or install path.")
        
    # Info Log
    out_abs = os.path.abspath(output_file)
    d_data = config.get("DOORS_DATA", "N/A")
    print(f"Target Module: {target_url}", file=sys.stderr)
    print(f"Output JSON:   {out_abs}", file=sys.stderr)
    print(f"DOORS Data:    {d_data}", file=sys.stderr)
    
    # If output_file is not absolute, make it absolute
    output_file = os.path.abspath(output_file)

    # Build Command (GUI only, no DXL execution)
    cmd = [doors_exe]
    data = config.get("DOORS_DATA")

    print(
        "Fallback mode: DOORS will use GUI login (manual username/password input).",
        file=sys.stderr,
    )
    if data:
        cmd.extend(["-data", data])

    # Keep GUI lightweight and visible
    cmd.extend(["-loglevel", "6", "-W"])

    # Capture Log file
    fd_log, log_path = tempfile.mkstemp(suffix=".log")
    os.close(fd_log)
    cmd.extend(["-logfile", log_path])

    print(f"Running DOORS process (Log: {log_path})...", file=sys.stderr)

    try:
        process = subprocess.Popen(cmd)
    except Exception as e:
        print(f"\nError launching DOORS: {e}", file=sys.stderr)
        sys.exit(1)

    # Wait for process visibility first
    print("Waiting for DOORS process to launch...", file=sys.stderr)
    if not wait_for_doors_process(timeout_sec=30):
        print("Error: DOORS process not detected within 30 seconds.", file=sys.stderr)
        sys.exit(1)

    # Poll COM availability and extract only after COM is available
    print("DOORS process detected. Polling COM connection...", file=sys.stderr)
    max_retries = 50
    retry_interval = 30
    for attempt in range(1, max_retries + 1):
        # If user closed DOORS during login/polling, stop early
        ret = process.poll()
        if ret is not None:
            print(f"Error: DOORS exited before COM became available (code {ret}).", file=sys.stderr)
            if os.path.exists(log_path):
                with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:
                    print(f"--- DOORS LOG ---\n{f.read()}", file=sys.stderr)
            sys.exit(1)

        print(f"Polling COM connection (attempt {attempt}/{max_retries})...", file=sys.stderr)
        success, msg = try_com_extraction(target_url, output_file)
        if success:
            print(msg, file=sys.stderr)
            print("DOORS remains open by design after extraction.", file=sys.stderr)
            return

        if attempt < max_retries:
            print(f"COM attempt {attempt} failed: {msg}. Retrying in {retry_interval}s...", file=sys.stderr)
            time.sleep(retry_interval)

    print("Error: COM polling exhausted before login/session became available.", file=sys.stderr)
    sys.exit(1)


# =============================================================================
# CLI INTERFACE
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description="DOORS Extraction Tool")
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    # Subcommand: Extract
    p_extract = subparsers.add_parser('extract', help="Extract raw data from DOORS")
    p_extract.add_argument('--url', required=True, help="DOORS URL or Module Path")
    p_extract.add_argument('--output', required=True, help="Path for raw JSON output")
    p_extract.add_argument('--no-gui', action='store_true',
                           help="COM-only mode: do NOT launch DOORS GUI if COM unavailable. "
                                "Use this as default safety net; drop the flag only after "
                                "user has explicitly consented to GUI launch.")
    
    args = parser.parse_args()
    
    if args.command == "extract":
        target = parse_doors_url(args.url)
        run_extraction(target, args.output, no_gui=args.no_gui)

if __name__ == "__main__":
    main()
