#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PatentDiagramGenerator — Patent-style technical diagrams via Graphviz.

Implements the API documented in patent-diagram-generator/SKILL.md:
  - create_flowchart(steps, filename, output_format)
  - create_block_diagram(blocks, connections, filename, output_format)
  - render_dot_diagram(dot_code, filename, output_format, engine)
  - add_reference_numbers(svg_path, reference_map)
  - get_diagram_templates()

Patent compliance (37 CFR §1.84 + CNIPA 中国专利审查指南):
  - B&W only (black ink on white), no color
  - Reference numbers 10/20/30... (main), 12/14/16 (sub under 10)
  - Sharp rectangles (CNIPA preference), ellipse for start/end, diamond for decision
  - Clear orthogonal routing via splines='polyline'
  - Distinct visual channels for main flow / feedback / lead lines

Requires: Graphviz `dot` binary on PATH + Python `graphviz` package.
"""

from __future__ import annotations

import os
import re
import sys
import platform
import subprocess
import tempfile
import warnings
import graphviz
from typing import Optional

# Reference-number heuristic: pull trailing (NN) from a node label.
_REF_RE = re.compile(r"\((\d+)\)\s*$")

# Unicode misc-symbols + dingbats range (U+2600–U+27BF): ✓✗⚠⭐➜✅❌⛔
# SimHei lacks glyphs here → Graphviz HTML labels emit raw codepoint (e.g. "2713").
# Plain-text node labels usually survive; HTML labels break. See compliance.md row 4.
_SYMBOL_DANGER_ZONE = re.compile(r'[\u2600-\u27BF]')


# ---------------------------------------------------------------------------
# CJK font resolution — fixes 文字乱码 (tofu/??? mojibake) in rendered PNG/SVG.
#
# Root cause: Graphviz on Windows uses fontconfig + pango/cairo. The stock
# Graphviz install ships NO fonts.conf, so fontconfig cannot find CJK font
# families like "SimSun" even when simsun.ttc exists in C:\Windows\Fonts.
# Result: every Chinese glyph renders as tofu □□□ or ???. The fix is to write
# a fonts.conf that (a) points fontconfig at C:\Windows\Fonts, and (b) maps
# the requested family name to the actual file via <match> rules.
# ---------------------------------------------------------------------------

# Candidate (family_name, file_path) pairs, in preference order.
# The first pair whose file exists wins. Preference is given to fonts that
# Graphviz's pango/cairo backend loads WITHOUT warnings on a stock Windows
# install (verified empirically): SimHei > Microsoft YaHei > SimSun. SimSun
# (simsun.ttc) sometimes loads as tofu because the .ttc collection's primary
# face name isn't always picked up; SimHei (single .ttf) is the most reliable.
_CJK_CANDIDATES = [
    # Windows — SimHei first (most reliable single-file TTF, no Pango warnings)
    ("SimHei", r"C:\Windows\Fonts\simhei.ttf"),
    ("Microsoft YaHei", r"C:\Windows\Fonts\msyh.ttc"),
    ("SimSun", r"C:\Windows\Fonts\simsun.ttc"),
    ("DengXian", r"C:\Windows\Fonts\Deng.ttf"),
    # Linux (Noto / WenQuanYi when fc-list absent)
    ("Noto Sans CJK SC", "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"),
    ("WenQuanYi Micro Hei", "/usr/share/fonts/wqy-microhei/wqy-microhei.ttc"),
    # macOS
    ("PingFang SC", "/System/Library/Fonts/PingFang.ttc"),
    ("STHeiti", "/System/Library/Fonts/STHeiti Medium.ttc"),
]

_FONTSCONF_TEMPLATE = """<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- Auto-generated by patent-diagram-generator/diagram_generator.py
     Maps the CJK family "{family}" to {file} so Graphviz renders CJK glyphs. -->
<fontconfig>
  <dir>{fontdir}</dir>
  <cachedir>{cachedir}</cachedir>
  <match target="pattern">
    <test name="family"><string>{family}</string></test>
    <edit name="file" mode="assign" binding="strong"><string>{file}</string></edit>
  </match>
  <match target="pattern">
    <test name="family"><string>sans-serif</string></test>
    <edit name="family" mode="append" binding="weak"><string>{family}</string></edit>
  </match>
</fontconfig>
"""


def _resolve_cjk_font() -> str:
    """Return a CJK font family name that renders on this machine.

    Side effect: on Windows it writes a fonts.conf and exports FONTCONFIG_FILE
    so that graphviz's fontconfig backend can find the font file. This MUST be
    called before any graphviz render.
    """
    chosen_family = "SimSun"  # safe default; fontconfig falls back if missing
    for family, path in _CJK_CANDIDATES:
        if path and os.path.exists(path):
            chosen_family = family
            # On Windows, install a fontconfig mapping so fontconfig can resolve
            # the family name to the actual file (Graphviz ships no fonts.conf).
            if platform.system() == "Windows":
                try:
                    fontdir = os.path.dirname(path) or r"C:\Windows\Fonts"
                    cachedir = os.path.join(tempfile.gettempdir(), "fontconfig_cache")
                    os.makedirs(cachedir, exist_ok=True)
                    conf_path = os.path.join(
                        tempfile.gettempdir(),
                        "patent_diagram_fonts.conf",
                    )
                    conf_text = _FONTSCONF_TEMPLATE.format(
                        family=family, file=path, fontdir=fontdir, cachedir=cachedir,
                    )
                    with open(conf_path, "w", encoding="utf-8") as f:
                        f.write(conf_text)
                    os.environ["FONTCONFIG_FILE"] = conf_path
                except Exception:
                    pass  # best-effort; render may still fall back
            break
    return chosen_family


# Resolve once at import time so every render uses a working font.
CJK_FONT = _resolve_cjk_font()


class PatentDiagramGenerator:
    """Generate USPTO/CNIPA-compliant patent figures with Graphviz.

    Style constants are intentionally hard-coded (not caller-configurable)
    to ensure visual consistency with patent-forge disclosure conventions.
    Font: SimHei (黑体) — matches patent-forge heading font.
    Font size: 14pt — matches patent-forge H2 heading (37 CFR §1.84(p)(3) min).
    """

    # ═══ Graph-level defaults ═══
    # splines=polyline: orthogonal routing, keeps edge labels (forge §2.2)
    # penwidth=1.3:       "线条均匀、清晰、足够深" (forge 00-baseline §2.2)
    GRAPH_ATTRS = {
        "splines": "polyline",
        "nodesep": "0.35",
        "ranksep": "0.55",
        "bgcolor": "white",
        "fontname": CJK_FONT,
        "fontsize": "14",
        "penwidth": "1.3",
        "dpi": "300",
    }

    # ═══ Node base — shared by all node shapes ═══
    # margin=0.15,0.1: comfortable text padding inside nodes
    _NODE_BASE = {
        "style": "filled",
        "fillcolor": "white",
        "fontname": CJK_FONT,
        "fontsize": "14",
        "penwidth": "1.3",
        "margin": "0.15,0.1",
    }

    BOX_ATTRS = {**_NODE_BASE, "shape": "box"}
    ELLIPSE_ATTRS = {**_NODE_BASE, "shape": "ellipse", "width": "1.9", "height": "0.7"}
    DIAMOND_ATTRS = {**_NODE_BASE, "shape": "diamond", "fontsize": "13", "width": "2.0", "height": "1.0"}

    def __init__(self, output_dir: str = "."):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _new_graph(self, name: str, rankdir: str, label: str = "") -> graphviz.Digraph:
        g = graphviz.Digraph(name, format="svg")
        g.attr(rankdir=rankdir, **self.GRAPH_ATTRS)
        # CRITICAL: graph.fontname does NOT cascade to node/edge labels in
        # Graphviz — each element class has its own default. If node/edge
        # fontname is not set, they fall back to "Times Roman", which lacks
        # CJK glyphs → edge labels render as tofu/??? (文字乱码). Set the CJK
        # font explicitly on ALL three classes.
        g.attr("node", fontname=self.GRAPH_ATTRS["fontname"])
        g.attr("edge", fontname=self.GRAPH_ATTRS["fontname"],
               fontsize="13",           # edge labels slightly smaller than nodes
               arrowhead="vee",         # clean patent-figure arrow (forge 02-electronic §2.4)
               arrowsize="0.9",
        )
        if label:
            g.attr(label=label, labelloc="b", fontsize="13")
        return g

    def _render(self, g: graphviz.Digraph, filename: str, output_format: str) -> str:
        """Render the graph and ALWAYS emit both svg + png.

        Dual-output policy (skill convention): SVG is the primary, editable
        deliverable; PNG is required for the view_image verification gate and
        for embedding in docx/pptx downstream. Rather than relying on callers
        to remember to request png separately, we produce both on every render.

        Returns the path matching the caller's requested `output_format`
        (preserved for backward compatibility), but both files always exist.
        """
        path = os.path.join(self.output_dir, filename)
        # Primary render in the requested format.
        g.render(path, format=output_format, cleanup=True)
        # Always emit the complementary format so svg↔png are both present.
        for fmt in ("svg", "png"):
            if fmt != output_format:
                try:
                    g.render(path, format=fmt, cleanup=True)
                except Exception:
                    # Best-effort: a missing companion format must not abort
                    # the primary render. The primary file already exists.
                    pass
        # GATE 2 auto-check: suspiciously small SVG → likely tofu/empty render.
        svg_path = f"{path}.svg"
        if os.path.exists(svg_path):
            svg_size = os.path.getsize(svg_path)
            if svg_size < 500:
                raise RuntimeError(
                    f"SVG render is only {svg_size} bytes (expected ≥500). "
                    f"Likely font/tofu failure — check CJK font config. "
                    f"See Failure Mode row 3 in references/compliance.md."
                )
        return f"{path}.{output_format}"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def _validate_refs_and_symbols(self, elements, figure_type="figure"):
        """Check duplicate ref numbers + Unicode symbol danger zone.

        elements: list of dicts with optional 'ref' (int) and 'label' (str).
        Raises ValueError on duplicate refs; emits UserWarning on symbols.
        """
        refs = [e.get("ref") for e in elements if e.get("ref")]
        seen = set()
        dups = {r for r in refs if r in seen or seen.add(r)}
        if dups:
            raise ValueError(
                f"Duplicate reference numbers in {figure_type}: {sorted(dups)}. "
                f"Each number = exactly ONE element per figure (CNIPA/USPTO rule)."
            )
        if len(refs) > 3:
            warnings.warn(
                f"{figure_type} has {len(refs)} reference numbers. "
                f"Recommend ≤3 per figure to avoid crossing lead lines. "
                f"See Anti-Pattern #3 in references/compliance.md.",
                UserWarning, stacklevel=3,
            )
        for e in elements:
            label = e.get("label", "")
            if _SYMBOL_DANGER_ZONE.search(label):
                bad = _SYMBOL_DANGER_ZONE.findall(label)
                warnings.warn(
                    f"Label '{label}' contains Unicode symbols {bad!r} "
                    f"(U+2600–U+27BF). SimHei lacks glyphs for these — "
                    f"may render as raw codepoints in HTML labels. "
                    f"Use CJK text or ASCII instead. "
                    f"See compliance.md Failure Mode row 4.",
                    UserWarning, stacklevel=3,
                )

    def create_flowchart(self, steps, filename="flowchart", output_format="svg"):
        """Create a method-step flowchart.

        steps: list of dicts with keys:
            id, label, shape (ellipse|box|diamond|parallelogram|cylinder),
            next (list of {id, label?}), ref (optional patent number, e.g. 10)
        """
        self._validate_refs_and_symbols(steps, figure_type="flowchart")
        g = self._new_graph(filename, rankdir="TB")
        shape_attr = {
            "ellipse": self.ELLIPSE_ATTRS,
            "box": self.BOX_ATTRS,
            "diamond": self.DIAMOND_ATTRS,
            "parallelogram": dict(self.BOX_ATTRS, shape="parallelogram"),
            "cylinder": dict(self.BOX_ATTRS, shape="cylinder"),
        }
        for s in steps:
            attrs = dict(shape_attr.get(s.get("shape", "box"), self.BOX_ATTRS))
            label = s["label"]
            if s.get("ref"):
                label = f"{label}\\n({s['ref']})"
            g.node(s["id"], label, **attrs)
        for s in steps:
            for nxt in s.get("next", []):
                if isinstance(nxt, str):
                    g.edge(s["id"], nxt)
                else:
                    style = nxt.get("style", "solid")
                    g.edge(s["id"], nxt["id"], label=nxt.get("label", ""),
                           style=style, constraint=nxt.get("constraint", "true"))
        return self._render(g, filename, output_format)

    def create_block_diagram(self, blocks, connections, filename="block",
                             output_format="svg", rankdir="LR", title=""):
        """Create a system block diagram.

        blocks: list of {id, label, type (input|output|process|storage|decision|default),
                          ref (optional number)}
        connections: list of [from_id, to_id, label?] or
                     [from_id, to_id, label, style]
        """
        self._validate_refs_and_symbols(blocks, figure_type="block diagram")
        g = self._new_graph(filename, rankdir=rankdir, label=title)
        for b in blocks:
            label = b["label"]
            if b.get("ref"):
                label = f"{label}\\n({b['ref']})"
            g.node(b["id"], label, **self.BOX_ATTRS)
        for conn in connections:
            frm, to = conn[0], conn[1]
            lbl = conn[2] if len(conn) > 2 else ""
            style = conn[3] if len(conn) > 3 else "solid"
            g.edge(frm, to, label=lbl, style=style)
        return self._render(g, filename, output_format)

    def render_dot_diagram(self, dot_code, filename="custom", output_format="svg",
                           engine="dot"):
        """Render raw DOT source. Always emits both svg + png (dual-output
        policy — see `_render` docstring). Returns the path matching the
        requested `output_format`."""
        path = os.path.join(self.output_dir, filename)
        # Primary render in the requested format.
        g = graphviz.Source(dot_code, format=output_format, engine=engine)
        g.render(path, cleanup=True)
        # Always emit the complementary format.
        for fmt in ("svg", "png"):
            if fmt != output_format:
                try:
                    g2 = graphviz.Source(dot_code, format=fmt, engine=engine)
                    g2.render(path, cleanup=True)
                except Exception:
                    pass
        return f"{path}.{output_format}"

    def add_reference_numbers(self, svg_path, reference_map):
        """Inject patent-style reference numbers into an SVG file.

        reference_map: {node_label_substring: number}
        Appends '(NN)' into the matching <text> elements if not already present.
        Returns the (possibly modified) svg_path.

        .. deprecated::
            Use in-label ``ref=`` on node/block dicts instead — cleaner, no
            lead-line crossing.  See Anti-Pattern #6 in references/compliance.md.
        """
        warnings.warn(
            "add_reference_numbers() is deprecated. Use in-label ref= on node/block "
            "dicts instead (e.g. {'id':'cpu','label':'处理器','ref':20}). "
            "See Anti-Pattern #6 in references/compliance.md.",
            DeprecationWarning, stacklevel=2,
        )
        if not os.path.exists(svg_path):
            raise FileNotFoundError(svg_path)
        with open(svg_path, "r", encoding="utf-8") as f:
            content = f.read()
        changed = False
        for needle, num in reference_map.items():
            tag = f"({num})"
            # Find <text>...</text> blocks whose inner text contains the needle
            # and does not already end with (num).
            def _inject(m):
                inner = m.group(2)
                if needle in inner and not inner.rstrip().endswith(tag):
                    return f"{m.group(1)}{inner} {tag}{m.group(3)}"
                return m.group(0)
            new = re.sub(r"(<text[^>]*>)(.*?)(</text>)", _inject, content,
                         flags=re.DOTALL)
            if new != content:
                changed = True
                content = new
        if changed:
            with open(svg_path, "w", encoding="utf-8") as f:
                f.write(content)
        return svg_path

    def get_diagram_templates(self):
        """Return ready-made template definitions for common patent figures."""
        return {
            "simple_flowchart": [
                {"id": "start", "label": "开始", "shape": "ellipse", "next": ["s1"]},
                {"id": "s1", "label": "步骤 S1", "shape": "box", "next": ["s2"]},
                {"id": "s2", "label": "步骤 S2", "shape": "box", "next": ["end"]},
                {"id": "end", "label": "结束", "shape": "ellipse", "next": []},
            ],
            "system_block": {
                "blocks": [
                    {"id": "in", "label": "输入单元", "type": "input", "ref": 10},
                    {"id": "cpu", "label": "处理单元", "type": "process", "ref": 20},
                    {"id": "out", "label": "输出单元", "type": "output", "ref": 30},
                ],
                "connections": [["in", "cpu"], ["cpu", "out"]],
            },
            "method_steps": [
                {"id": "s0", "label": "接收输入", "shape": "parallelogram", "next": ["s1"]},
                {"id": "s1", "label": "处理", "shape": "box", "next": ["d"]},
                {"id": "d", "label": "是否满足?", "shape": "diamond", "next": ["s2", "s0"]},
                {"id": "s2", "label": "输出结果", "shape": "parallelogram", "next": []},
            ],
            "component_hierarchy": {
                "blocks": [
                    {"id": "top", "label": "系统", "type": "process", "ref": 10},
                    {"id": "a", "label": "子系统 A", "type": "process", "ref": 12},
                    {"id": "b", "label": "子系统 B", "type": "process", "ref": 14},
                ],
                "connections": [["top", "a"], ["top", "b"]],
            },
        }


if __name__ == "__main__":
    # Smoke test
    gen = PatentDiagramGenerator(output_dir=".")
    tmpl = gen.get_diagram_templates()
    gen.create_flowchart(tmpl["simple_flowchart"], filename="_smoke_flow")
    gen.create_block_diagram(**tmpl["system_block"], filename="_smoke_block")
    print("PatentDiagramGenerator smoke test OK")
